### ISSUE TITLE
Enable Client certificate verification with TLS

### ISSUE THREAD

**Issue by ardesai** [stilliard/docker-pure-ftpd#108]
I have certificate and keys set up for server verification however I would like to verify the client purely using certificate and avoid passwords.

How do I enable the client certificate verification and where do I add or specify the location of the client verification on the server.

**Comment by stilliard** [comment]
Hey @ardesai 
Sorry I didn't spot your post before, not sure if you've already solved this but I'm not actually sure about that question. As it's more of a general ftp/pure-ftp problem rather than a docker specific one I think you'd have more luck on stackoverflow with the pureftpd tag, hope this helps.
