### ISSUE TITLE
"Sorry, but I can't trust you" issue

### ISSUE THREAD

**Issue by lbluenote** [stilliard/docker-pure-ftpd#181]
image: stilliard/pure-ftpd:hardened

I tried everithings but i can't connect, log says:

Mar 10 16:25:09 e2f1fe1fc920 pure-ftpd: (?@*****) [INFO] TLS: Enabled TLSv1.3 with TLS_AES_256_GCM_SHA384, 256 secret bits cipher
Mar 10 16:25:09 e2f1fe1fc920 pure-ftpd: (?@*****) [DEBUG] Command [user] [*******]
Mar 10 16:25:09 e2f1fe1fc920 pure-ftpd: (?@*****) [DEBUG] Command [pass] [<*>]
Mar 10 16:25:09 e2f1fe1fc920 pure-ftpd: (?@*****) [WARNING] Sorry, but I can't trust you

I see in the pureftp faq:

* "Sorry, I can't trust you".

-> When a user tries to log in, he gets "Sorry, I can't trust you". But his
login/password pair is right. What wrong?

That message can means two things:

- The user has a shell that isn't listed in /etc/shells. You must add it,
even if it's a fake shell like /bin/false . Also make sure that you have a
carriage return after the last entry in /etc/shells.

- You are using the -u <uid> option to deny access to users whose uid is
below <uid> . But the user you are trying to log in as, has an uid in the
forbidden range.

**Comment by stilliard** [comment]
Hi @lbluenote 
Sorry for the delayed reply.

Have you tried the default/latest tag instead of the hardened one?
Instead of `image: stilliard/pure-ftpd:hardened` could you test with `image: stilliard/pure-ftpd` please.

The difference is just a few extra flags but maybe one of those is causing an issue (comparison of flags between the 2 https://github.com/stilliard/docker-pure-ftpd/compare/master..hardened)

**Comment by lbluenote** [comment]
After a lot of tests with all tags, it start working after I delete pureftpd.passwd file. Maybe uid guid related probelms... sorry.
Thank you so much.
