### ISSUE TITLE
password change does not work

### ISSUE THREAD

**Issue by EugenMayer** [stilliard/docker-pure-ftpd#42]
doing a password change with

```pure-pw passwd myuser -f /etc/pure-ftpd/passwd/pureftpd.passwd```

Does finish - but will not work.

Probably related, list wont work either, it tells me, it cannot read the passwd file:

```pure-pw passwd list -f /etc/pure-ftpd/passwd/pureftpd.passwd```

**Comment by stilliard** [comment]
Hi @EugenMayer , sorry for the delay. 

I believe the password change needs -m at the end to update the password file, bit weird but should work. 

Also I think the issue with the list command may just be it's "pure-pw list" rather than "pure-pw passwd list", hope that helps. 

I'll update the docs now though about the change password stuff as others may run into this too, thanks for mentioning this!
