### ISSUE TITLE
Failed to retrieve directory listing

### ISSUE THREAD

**Issue by Casy** [stilliard/docker-pure-ftpd#47]
Hi, i have this issue:

Status:      	Retrieving directory listing...
Command:	PWD
Response: 	257 "/" is your current location
Command:	TYPE I
Response: 	200 TYPE is now 8-bit binary
Command:	PASV
Error:        	Connection timed out after 20 seconds of inactivity
Error:        	Failed to retrieve directory listing

I try to connect with FileZilla. any idea?

**Comment by Mesqualito** [comment]
Did you:
- open the passive ports (like described) from the container to the docker-host, so that pure-ftpd can take them to serve one (or more) ftp-data-port(s) to the ftp-client?
- open up your firewall on the docker-host to allow connection to these ports?

Perhaps you can also try to use FileZilla in active mode, where pure-ftpd uses port 20 to connect back to your client for data-transfer, so you have to care for your firewall-ports on your ftp-client. The server firewall also needs to be open at Port 20.

**Comment by stilliard** [comment]
Hi @Casy , hope @Mesqualito's answer was able to help you. 
Closing this ticket for now but please re-open if there's any issue still, thank you.

**Comment by jdbenn** [comment]
For anyone else finding this - as @stilliard  states - you need to open port 21 and 30000:30009 on both the container AND the host.  Now if you are also hosting in any of the cloud platforms - Azure, AWS or GCP - you will likely need to open up the ports on their firewalls / security groups / acl's.  In my case I forgot about the 30000:30009 allow entry on my EC2 security group in AWS.
