### ISSUE TITLE
Can't increase max clients with run.sh

### ISSUE THREAD

**Issue by weeix** [stilliard/docker-pure-ftpd#99]
Hello,

I started the container with this command (it's from README.md, but changed the published ports from 30000-30009 to 30000-30059):

```
docker run --rm -d --name ftpd_server -p 21:21 -p 30000-30059:30000-30059 stilliard/pure-ftpd:hardened bash /run.sh -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30059
```

The command above should start a ftp server with 30 max clients.

However, the result from `docker logs ftpd_server` stated that the max clients = 5:

> Setting default max clients to: 5
> Starting Pure-FTPd:
>   pure-ftpd -c 30 -C 10 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30059   -c 5

(Please note the additional `-c 5` parameter)

And some result from `ftp 192.168.99.100` which confirmed that only 5 clients would be allowed:

> Connected to 192.168.99.100.
> 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
> 220-You are user number 1 of 5 allowed.
> 220-Local time is now 05:13. Server port: 21.
> 220-This is a private system - No anonymous login
> 220-IPv6 connections are also welcome on this server.
> 220 You will be disconnected after 15 minutes of inactivity.
> 200 OK, UTF-8 enabled
> User (192.168.99.100:(none)):

Docker version 18.03.0-ce, build 0520e24302

Thanks for maintaining this Docker image.

**Comment by stilliard** [comment]
Hi @weeix 
Thanks for reporting this, turns out our check to see if " -c " is set was not matching due to us checking for a space before it & it was the first flag so no space.
I've pushed a fix by forcing a space in at the front but i'll spend some time soon to better match flags passed in in a more sane way. 
For now at least it should now let you increase the max clients :+1:
